# Generated by Django 2.2.2 on 2019-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input_text', models.CharField(max_length=100)),
                ('detected_intent', models.CharField(max_length=255)),
                ('detected_intent_confidence', models.CharField(max_length=255)),
                ('chatbot_output_text', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
